name: ant_connect
description: "Connect to the decentralized P2P Foundation network using human-friendly three-word addresses"
publish_to: 'none'
version: 1.0.0+1
homepage: https://github.com/dirvine/p2p
repository: https://github.com/dirvine/p2p
issue_tracker: https://github.com/dirvine/p2p/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true